name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ main , test , master]
  pull_request:
    branches: [ main ]

jobs:
  # -------- CI Stage --------
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get the app version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version: \"$VERSION\"" > version.yaml
          ls -l

      - name: Upload version artifact
        uses: actions/upload-artifact@v4
        with:
          name: version
          path: version.yaml

  config-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2  



  build:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download version artifact
        uses: actions/download-artifact@v4
        with:
          name: version

      - name: Load version into env
        run: |
          VERSION=$(grep 'version' version.yaml | awk -F'"' '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Using VERSION: $VERSION"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Package app artifact
        run: |
          ARTIFACT_NAME="nodeapp-${VERSION}-${GITHUB_SHA:0:7}.tgz"
          mkdir -p artifacts
          mkdir -p artifact-temp
          shopt -s extglob
          cp -r !(artifact-temp|artifacts|.git|.github) artifact-temp/
          tar -czf "artifacts/$ARTIFACT_NAME" -C artifact-temp .
          rm -rf artifact-temp
          ls -R artifacts

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: artifacts/


  # -------- Docker Build & Push --------
  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: app-build

      - name: Download version artifact
        uses: actions/download-artifact@v4
        with:
          name: version

      - name: Debug downloaded files
        run: |
          echo "Downloaded files:"
          ls -l

      - name: Extract app artifact
        run: |
          mkdir -p app
          tar -xzf $(ls nodeapp-*.tgz | head -n 1) -C app

      - name: Load VERSION into environment
        run: |
          VERSION=$(grep 'version' version.yaml | awk -F'"' '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Loaded VERSION=$VERSION"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2  

      - name: Build & Push Docker Image to ecr
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.ECR_URL }}/nodeapp:${{ env.VERSION }}

  # -------- promot the image if master branch--------
  promot:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    outputs:
      latest_tag: ${{ steps.extract.outputs.latest_tag }}
      base_tag: ${{ steps.extract.outputs.base_tag }}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2  

      - name: Get latest test image tag
        id: extract
        run: |
          LATEST_TAG=$(aws ecr describe-images \
            --repository-name nodeapp \
            --region eu-central-1 \
            --output json |
          jq -r '
            .imageDetails[]
            | select(.imageTags != null)
            | select([.imageTags[] | contains("test")] | any)
            | {pushedAt: .imagePushedAt, tag: (.imageTags[] | select(contains("test")))}
          ' | jq -s 'sort_by(.pushedAt) | last.tag')

          
          LATEST_TAG=$(echo "$LATEST_TAG" | tr -d '"')
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_OUTPUT
          echo "LATEST_TAG=$LATEST_TAG"

          BASE_TAG="${LATEST_TAG%-test}"
          echo "export BASE_TAG=$BASE_TAG" >> $GITHUB_OUTPUT
          echo "export BASE_TAG=$BASE_TAG"

  push-promoted-image:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: promot
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2  

      - name: Push Docker Image to ecr
        run: |
            docker pull ${{ secrets.ECR_URL }}/nodeapp:${{ needs.promot.outputs.LATEST_TAG }}
            docker tag ${{ secrets.ECR_URL }}/nodeapp:${{ needs.promot.outputs.LATEST_TAG }}  \
                    ${{ secrets.ECR_URL }}/nodeapp:${{ needs.promot.outputs.base_tag }}
            docker push ${{ secrets.ECR_URL }}/nodeapp:${{ needs.promot.outputs.base_tag }}

      

  # -------- Deploy to Server via SSH --------
  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Download version artifact
        uses: actions/download-artifact@v4
        with:
          name: version
          
      - name: Load VERSION into environment
        run: |
          VERSION=$(grep 'version' version.yaml | awk -F'"' '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Loaded VERSION=$VERSION"

      - name: Deploy via SSH to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Pull latest image"
            docker pull ${{ secrets.ECR_URL }}/nodeapp:${{ env.VERSION }}

            echo "Stop and remove old container"
            docker stop nodeapp || true
            docker rm nodeapp || true

            echo "Run new container"
            docker run -d --restart unless-stopped \
              -p 80:3000 \
              --name nodeapp \
              ${{ secrets.ECR_URL }}/nodeapp:${{ env.VERSION }}
